### ISSUE TITLE
Commands crashes when called from Android application

### ISSUE THREAD

**Issue by kyriog** [interactions-py/interactions.py#97]
Using discord-py-slash-command, release 1.0.9, calling a command with options from the Android app (version 61.1) raises an exception:
```
Ignoring exception in on_socket_response
Traceback (most recent call last):
  File "lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "lib\site-packages\discord_slash\client.py", line 741, in on_socket_response
    args = await self.process_options(ctx.guild, to_use["data"]["options"], selected_cmd.connector) \
  File "lib\site-packages\discord_slash\client.py", line 652, in process_options
    if x["type"] not in types:
KeyError: 'type'
```

It seems that from the mobile app (I don’t know if that occurs from iOS app too), Discord doesn’t send the "type" of an option in the response.

I’ve made a workaround on my side that solves my problem:
```python
# discord_slash/client.py
    async def on_socket_response(self, msg):
    […]
            if "options" in to_use["data"]:
                for x in to_use["data"]["options"]:
                    if "type" not in x:
                        for option in selected_cmd.options:
                            if option["name"] == x["name"]:
                                x["type"] = option["type"]
                                break
                    if "value" not in x:
                        return await self.handle_subcommand(ctx, to_use)
    […]
```

It’s clearly not a good solution on a long term basis as it doesn’t handle subcommands which have probably the same problem, but it avoid adding complexity to the `process_options` method.

**Comment by ghost** [comment]
ohhh guy i have exactly same issue, also 3-2 days ago

**Comment by eunwoo1104** [comment]
Fixed and will release soon.

**Comment by quirky-bluejay** [comment]
Is this happening because not all clients are sending the type currently?
https://github.com/discord/discord-api-docs/issues/2383#issuecomment-776364193

**Comment by eunwoo1104** [comment]
I think yes. I forgot to check if all clients includes option type, and this happened I guess.

**Comment by LordOfPolls** [comment]
Hi, still having this issue on the latest version

Its worth noting i am using subcommands, I am unsure if the above commit handles them 

Update in case someone else finds themselves here: 

I made all my option names lower case and that fixed it.
